export const ADD_LOCATION = 'ADD_LOCATION';
export const LOAD_TABLE_DATA = 'LOAD_TABLE_DATA';
export const SEARCH_CITIES = 'SEARCH_CITIES';
export const SWITCH_TEMP_UNIT = 'SWITCH_TEMP_UNIT';
export const FLY_TO_LOCATION = 'FLY_TO_LOCATION';
export const LOG_USER_IN = 'LOG_USER_IN';
